### Extract Data

In [2]:
import pandas as pd

In [37]:
with open ('customers.csv', 'r') as f:
    customers = pd.read_csv(f)
customers

   customer_id first_name last_name        city  age            email
0            1      Ahmed    Hassan       Cairo   25  ahmed@email.com
1            2       Sara       Ali        Giza   31   sara@email.com
2            3       Omar   Mohamed       cairo   17   omar@email.com
3            4       Mona   Ibrahim  Alexandria   28              NaN
4            5      Ahmed    Hassan       Cairo   25  ahmed@email.com

In [4]:
pip install pandas pyarrow

Requirement already satisfied: pandas in c:\users\anas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (3.0.2)
Requirement already satisfied: pyarrow in c:\users\anas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (25.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\anas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\anas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\anas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\anas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: C:\Users\Anas\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [8]:
with open ('orders.parquet', 'rb') as f:
    orders = pd.read_parquet(f)
orders

    order_id  customer_id  product_id  quantity order_date
0       1001            1         101         2 2026-09-01
1       1002            2         102         1 2026-09-01
2       1003            3         103         3 2026-09-02
3       1004            4         101         1 2026-09-02
4       1005            1         104         2 2026-09-03
5       1006            5         102         1 2026-09-03
6       1007            2         105         4 2026-09-04
7       1008            3         101         1 2026-09-04
8       1009            4         103         2 2026-09-05
9       1010            1         104         1 2026-09-05
10      1003            3         103         3 2026-09-02

In [9]:
url ='https://raw.githubusercontent.com/MohammedHameds/test1455/refs/heads/main/products.csv'
Products = pd.read_csv(url)
Products

   product_id product_name     category  unit_price
0         101       Laptop  Electronics       25000
1         102        Mouse  Accessories         500
2         103     Keyboard  Accessories        1200
3         104      Monitor  Electronics        7000
4         105   Headphones  Accessories        2500
5         106       Webcam  Accessories        1800

In [10]:
customers

   customer_id first_name last_name        city  age            email
0            1      Ahmed    Hassan       Cairo   25  ahmed@email.com
1            2       Sara       Ali        Giza   31   sara@email.com
2            3       Omar   Mohamed       cairo   17   omar@email.com
3            4       Mona   Ibrahim  Alexandria   28              NaN
4            5      Ahmed    Hassan       Cairo   25  ahmed@email.com

In [11]:
orders

    order_id  customer_id  product_id  quantity order_date
0       1001            1         101         2 2026-09-01
1       1002            2         102         1 2026-09-01
2       1003            3         103         3 2026-09-02
3       1004            4         101         1 2026-09-02
4       1005            1         104         2 2026-09-03
5       1006            5         102         1 2026-09-03
6       1007            2         105         4 2026-09-04
7       1008            3         101         1 2026-09-04
8       1009            4         103         2 2026-09-05
9       1010            1         104         1 2026-09-05
10      1003            3         103         3 2026-09-02

In [12]:
Products

   product_id product_name     category  unit_price
0         101       Laptop  Electronics       25000
1         102        Mouse  Accessories         500
2         103     Keyboard  Accessories        1200
3         104      Monitor  Electronics        7000
4         105   Headphones  Accessories        2500
5         106       Webcam  Accessories        1800

### Transformations

In [40]:
customers

,customer_id,first_name,last_name,city,age,email,full_name
0,1,Ahmed,Hassan,Cairo,25,ahmed@email.com,Ahmed Hassan
1,2,Sara,Ali,Giza,31,sara@email.com,Sara Ali
2,3,Omar,Mohamed,cairo,17,omar@email.com,Omar Mohamed
3,4,Mona,Ibrahim,Alexandria,28,no email provided,Mona Ibrahim
4,5,Ahmed,Hassan,Cairo,25,ahmed@email.com,Ahmed Hassan

In [ ]:
customers = customers.drop_duplicates()
customers["age"] = pd.to_numeric(customers["age"])
customers["email"] = customers["email"].fillna("no email provided")
customers["full_name"] = customers["first_name"] + " " + customers["last_name"]

In [31]:
orders

   order_id  customer_id  product_id  quantity order_date
0      1001            1         101         2 2026-09-01
1      1002            2         102         1 2026-09-01
2      1003            3         103         3 2026-09-02
3      1004            4         101         1 2026-09-02
4      1005            1         104         2 2026-09-03
5      1006            5         102         1 2026-09-03
6      1007            2         105         4 2026-09-04
7      1008            3         101         1 2026-09-04
8      1009            4         103         2 2026-09-05
9      1010            1         104         1 2026-09-05

In [30]:
orders = orders.drop_duplicates()
orders["quantity"]=pd.to_numeric(orders["quantity"])
orders["order_date"] = pd.to_datetime(orders["order_date"])

In [42]:
Products

   product_id product_name     category  unit_price
0         101       Laptop  Electronics       25000
1         102        Mouse  Accessories         500
2         103     Keyboard  Accessories        1200
3         104      Monitor  Electronics        7000
4         105   Headphones  Accessories        2500
5         106       Webcam  Accessories        1800

In [41]:
Products = Products.drop_duplicates()
Products["unit_price"] = pd.to_numeric(Products["unit_price"])

In [48]:
Sales = pd.merge(customers, orders, on="customer_id" , how="inner")
Sales = pd.merge(Sales , Products , on="product_id" , how = "inner")

Sales

,customer_id,first_name,last_name,city,age,email,full_name,order_id,product_id,quantity,order_date,product_name,category,unit_price
0,1,Ahmed,Hassan,Cairo,25,ahmed@email.com,Ahmed Hassan,1001,101,2,2026-09-01,Laptop,Electronics,25000
1,1,Ahmed,Hassan,Cairo,25,ahmed@email.com,Ahmed Hassan,1005,104,2,2026-09-03,Monitor,Electronics,7000
2,1,Ahmed,Hassan,Cairo,25,ahmed@email.com,Ahmed Hassan,1010,104,1,2026-09-05,Monitor,Electronics,7000
3,2,Sara,Ali,Giza,31,sara@email.com,Sara Ali,1002,102,1,2026-09-01,Mouse,Accessories,500
4,2,Sara,Ali,Giza,31,sara@email.com,Sara Ali,1007,105,4,2026-09-04,Headphones,Accessories,2500
5,3,Omar,Mohamed,cairo,17,omar@email.com,Omar Mohamed,1003,103,3,2026-09-02,Keyboard,Accessories,1200
6,3,Omar,Mohamed,cairo,17,omar@email.com,Omar Mohamed,1008,101,1,2026-09-04,Laptop,Electronics,25000
7,4,Mona,Ibrahim,Alexandria,28,no email provided,Mona Ibrahim,1004,101,1,2026-09-02,Laptop,Electronics,25000
8,4,Mona,Ibrahim,Alexandria,28,no email provided,Mona Ibrahim,1009,103,2,2026-09-05,Keyboard,Accessories,1200
9,5,Ahmed,Hassan,Cairo,25,ahmed@email.com,Ahmed Hassan,1006,102,1,2026-09-03,Mouse,Accessories,500

In [49]:
Sales["total_amount"] = Sales["quantity"] * Sales["unit_price"]

In [52]:
Final_df = Sales[["order_id" ,"full_name","product_name" , "quantity" ,"unit_price" , "total_amount" ]]

In [58]:
Final_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      10 non-null     int64
 1   full_name     10 non-null     str
 2   product_name  10 non-null     str
 3   quantity      10 non-null     int64
 4   unit_price    10 non-null     int64
 5   total_amount  10 non-null     int64
dtypes: int64(4), str(2)
memory usage: 796.0 bytes

In [53]:
Final_df

   order_id     full_name product_name  quantity  unit_price  total_amount
0      1001  Ahmed Hassan       Laptop         2       25000         50000
1      1005  Ahmed Hassan      Monitor         2        7000         14000
2      1010  Ahmed Hassan      Monitor         1        7000          7000
3      1002      Sara Ali        Mouse         1         500           500
4      1007      Sara Ali   Headphones         4        2500         10000
5      1003  Omar Mohamed     Keyboard         3        1200          3600
6      1008  Omar Mohamed       Laptop         1       25000         25000
7      1004  Mona Ibrahim       Laptop         1       25000         25000
8      1009  Mona Ibrahim     Keyboard         2        1200          2400
9      1006  Ahmed Hassan        Mouse         1         500           500

### Load (SQL Server)

In [61]:
data = list(Final_df.itertuples(index=False, name=None))

In [54]:
import pyodbc

In [59]:
conn = pyodbc.connect(
    "Driver={ODBC Driver 17 for SQL Server};"
    "server=.\SQLEXPRESS;"
    "Database=FlaskDB;"
    "trusted_connection=yes;"
)
cursor = conn.cursor()
cursor.execute(
'''
CREATE TABLE Sales (

   order_id           INT ,
   full_name          VARCHAR(50)  ,
   product_name       VARCHAR(50)  ,
   quantity           INT ,
   unit_price         INT ,
   total_amount       INT 
)

'''
)        

conn.commit()
cursor.close()
conn.close()

In [62]:
conn = pyodbc.connect(
    "Driver={ODBC Driver 17 for SQL Server};"
    "server=.\SQLEXPRESS;"
    "Database=FlaskDB;"
    "trusted_connection=yes;"
)
cursor = conn.cursor()
cursor.executemany(
'''
Insert Into Sales Values (?,?,?,?,?,?)

'''
,data)        

conn.commit()
cursor.close()
conn.close()

In [68]:
conn = pyodbc.connect(
    "Driver={ODBC Driver 17 for SQL Server};"
    "server=.\SQLEXPRESS;"
    "Database=FlaskDB;"
    "trusted_connection=yes;"
)
cursor = conn.cursor()
cursor.execute(
'''
SELECT * FROM Sales; 

'''
)        
conn.commit()
cursor.close()
conn.close()

### Flask Dashboard

In [77]:
from flask import Flask , render_template

app = Flask(__name__)

@app.route("/")
def dashboard() :
 
 conn = pyodbc.connect(
    "Driver={ODBC Driver 17 for SQL Server};"
    "server=.\SQLEXPRESS;"
    "Database=FlaskDB;"
    "trusted_connection=yes;"
 )
 cursor = conn.cursor()
 cursor.execute(
 '''
 SELECT * FROM Sales; 
 
 '''
 )   
 columns = [column[0] for column in cursor.description]
 rows = cursor.fetchall()     
 cursor.close()
 conn.close()

 return render_template(
    "dashboard.html",
    columns = columns , 
    rows = rows
)


if __name__ == "__main__":
    app.run(
        debug=True,
        use_reloader=False
    )

 * Serving Flask app '__main__'
 * Debug mode: on

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [22/Sep/2026 03:53:26] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2026 03:53:26] "GET /favicon.ico HTTP/1.1" 404 -